name: CI Lint

on:
  push:
    branches: [ main, ]
  pull_request:
    branches: [ '*', ]
  workflow_dispatch:

jobs:

  CI-Lint: 
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Checkout this Repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install .
        pip install flake8 pyproject-flake8

    - name: Lint with flake8
      run: |
        pflake8 bgtrees/ --count --statistics --verbose --config pyproject.toml
