name: Continuous Integration

on:
  push:
    branches: [ main, ]
  pull_request:
    branches: [ '*', ]
  workflow_dispatch:
    branches: [ main, ]

jobs:

  CI:
    runs-on: [self-hosted]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.10.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'

    - name: Checkout this Repo
      uses: actions/checkout@v4

    - name: Make CUDA discoverable
      run: |
        export CPATH="/usr/include/python3.10:${CPATH}"
        export CPATH="/home/docker/actions-runner/_work/_tool/Python/3.10.13/x64:${CPATH}"
        export PATH="/usr/local/cuda-12.2/bin:${PATH}"
        export LD_LIBRARY_PATH="/usr/local/cuda-12.2/lib64:${LD_LIBRARY_PATH}"
        echo "$PATH" && echo "$LD_LIBRARY_PATH" && nvcc --version && nvidia-smi
        ls /usr/include/python3.10
        ls /home/docker/actions-runner/_work/_tool/Python/3.10.13/x64

    - name: Install dependencies
      run: |
        pip install -e .[tests]
        pip install flake8 pyproject-flake8

    - name: Lint with flake8
      run: |
        pflake8 bgtrees/ --count --statistics --verbose

    - name: Test with pytest
      run: |
        pytest |& tee coverage.txt

    - name: Run update-badges script
      run: |
        python update-badges.py

    - name: Update badges and commit README.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: README.md
        commit_message: "Automatic badge update"
